// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClvlibH6NViSjbaCzpG3oEKKzwVSKjl98',
    appId: '1:448018727959:web:64b709dd28082feebe8852',
    messagingSenderId: '448018727959',
    projectId: 'comments-f6308',
    authDomain: 'comments-f6308.firebaseapp.com',
    storageBucket: 'comments-f6308.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0IrmHN8alwM5CYhj5vpEyUxtscNRdzQ',
    appId: '1:448018727959:android:082156fd2c038a91be8852',
    messagingSenderId: '448018727959',
    projectId: 'comments-f6308',
    storageBucket: 'comments-f6308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdCFAGAUMuK60-KKTQqfUs9vPFXDv_J4o',
    appId: '1:448018727959:ios:3862583a10c55421be8852',
    messagingSenderId: '448018727959',
    projectId: 'comments-f6308',
    storageBucket: 'comments-f6308.appspot.com',
    iosBundleId: 'com.example.commentsAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdCFAGAUMuK60-KKTQqfUs9vPFXDv_J4o',
    appId: '1:448018727959:ios:3862583a10c55421be8852',
    messagingSenderId: '448018727959',
    projectId: 'comments-f6308',
    storageBucket: 'comments-f6308.appspot.com',
    iosBundleId: 'com.example.commentsAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClvlibH6NViSjbaCzpG3oEKKzwVSKjl98',
    appId: '1:448018727959:web:2cb3bb0e43448afcbe8852',
    messagingSenderId: '448018727959',
    projectId: 'comments-f6308',
    authDomain: 'comments-f6308.firebaseapp.com',
    storageBucket: 'comments-f6308.appspot.com',
  );
}
